apiVersion: codeengine.cloud.ibm.com/v1beta1
kind: Application
metadata:
  name: weather-mcp-server
  labels:
    app: weather-mcp
spec:
  image: "your-registry/weather-mcp-python:latest"
  port: 8000
  env:
    - name: CODE_ENGINE
      value: "true"
  resources:
    requests:
      cpu: "0.25"
      memory: "0.5Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  scale:
    minInstances: 0
    maxInstances: 10
    initialInstances: 1
  probes:
    readiness:
      httpGet:
        path: /
        port: 8000
      initialDelaySeconds: 10
      periodSeconds: 5
    liveness:
      httpGet:
        path: /
        port: 8000
      initialDelaySeconds: 30
      periodSeconds: 10
