[project]
name = "weather-mcp-python"
version = "0.1.0"
description = "Weather MCP server"
readme = "README.md"
requires-python = ">=3.11.7"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]<=1.10.3",
    "fastmcp",
    "ibm-watsonx-orchestrate==1.8.1",
]