[project]
name = "weather-mcp-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.7"
dependencies = [
    "httpx>=0.24.0",
    "fastmcp>=0.1.0",
    "ibm-watsonx-orchestrate==1.11.0b0",
]
